config/routes.rb
Classical::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'

  resources :authentications, :only => [:create, :destroy]

  devise_for :users

  resource :user do
    resources :user_albums
  end

  resources :instruments do
    resources :discussions
  end

  resources :composers do
    resources :discussions
  end

  resources :obra_types do
    resources :discussions
  end

  resources :solists do
    resources :discussions
  end

  resources :directors do
    resources :discussions
  end

  resources :orchestras do
    resources :discussions
  end

  resources :albums do
    resources :discussions
    resources :user_albums, :only => [:new]
  end

  resources :user_albums

  resources :app_languages

  #TODO Refactor this routes!!!

  match 'composers/composers_completion/', :to =>  "composers#composers_completion"
  match 'composers/composers_completion/:prefix', :to =>  "composers#composers_completion"

  match 'obra_types/obra_type_completion/', :to =>  "obra_types#obra_type_completion"
  match 'obra_types/obra_type_completion/:prefix', :to =>  "obra_types#obra_type_completion"

  match 'solists/solist_completion/', :to =>  "solists#solist_completion"
  match 'solists/solist_completion/:prefix', :to =>  "solists#solist_completion"

  match 'directors/director_completion/', :to =>  "directors#director_completion"
  match 'directors/director_completion/:prefix', :to =>  "directors#director_completion"

  match 'orchestras/orchestra_completion/', :to =>  "orchestras#orchestra_completion"
  match 'orchestras/orchestra_completion/:prefix', :to =>  "orchestras#orchestra_completion"

  match 'instruments/instrument_completion/', :to =>  "instruments#instrument_completion"
  match 'instruments/instrument_completion/:prefix', :to =>  "instruments#instrument_completion"

  #END :)

  root :to => 'user_albums#index'
end

app/models/director.rb
# == Schema Information
#
# Table name: directors
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Director < ActiveRecord::Base
  has_many :albums
  has_many :discussions, :as => :discussable

  has_one :image, :as => :imageable

  accepts_nested_attributes_for :image, :allow_destroy => true

  validates :name, :presence => true, :uniqueness => true

  def to_s
    self.name
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_filter :find_director,  :only => [:show, :edit, :update, :destroy]

  def index
    @directors = Director.order(:name).page(params[:page])
  end

  def new
    @director = Director.new
  end

  def edit
  end

  def show
    conditions = {"album_director_id_equals" => @director.id}
    conditions.merge!(params[:search]) if params[:search] && params[:search][:album_director_id_equals]
    @user_album_search = current_user.user_albums.search(conditions)
    @user_albums = @user_album_search.page(params[:page])

    conditions = {"director_id_equals" => @director.id}
    conditions.merge!(params[:search]) if params[:search] && params[:search][:director_id_equals]
    @search = Album.search(conditions)
    @albums = @search.page(params[:page])
  end

  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to(@director, :notice => I18n.t('.create_msg')) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to(@director, :notice => I18n.t('.update_msg')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @director.destroy

     respond_to do |format|
       format.html { redirect_to(directors_url) }
     end
  end

  def director_completion
    matches = Director.search(:name_starts_with => params[:prefix])

    if matches.length == 0
      render :text => I18n.t(:no_results)
    else
      render :partial => matches.relation
    end
  end

  private

  def find_director
    @director = Director.find(params[:id])
  end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_director.html.haml
%tr
  %td= link_to director.name, director, :id => 'link_to_data'
  %td
    = link_to edit_director_path(director) do
      = image_tag 'edit.gif'
      = t(:edit)
  %td
    = link_to director, :confirm => t('delete_msg', :name => director.name), :method => :delete do
      = image_tag 'delete.gif'
      = t(:delete)

app/views/directors/_form.html.haml
.form
  %h2= t :director

  = form_for director do |f|
    = errors_for director
    .form_row
      = f.label :name
      = f.text_field :name, :class => :text

    .form_row
      = f.label :description
      = f.text_area :description, :class => :text

    .form_row_submit
      = f.submit :class => 'button'

= link_to t(:back), directors_path

app/views/directors/edit.html.haml
= title "#{t :editing} - #{@director.name}"

= render :partial => "form", :locals => { :director => @director }

app/views/directors/index.html.erb
<%= title t :directors %>
<h1><%= t :directors %></h1>

<p>
  <%= link_to t(:new), new_director_path %>
</p>

<%= form_tag nil, :class => 'search-form' do %>
  <%= t :search %>
  <%= text_field_tag :search_field %>
<% end -%>

<div class="paginator">
  <%= paginate @directors %>
</div>

<table class="data_table">
  <tr>
    <th><%= t :name %> </th>
    <th colspan=2><%= t :options %> </th>
  </tr>
  <tbody id="results">
    <%= render :partial => @directors %>
  </tbody>
</table>

<%= paginate @directors %>

<script type="text/javascript" language="javascript" charset="utf-8">
// <![CDATA[
  $(document).ready(function(){
    // when the #search field changes
    $("#search_field").live('keyup', function() {
      // make a POST call and replace the content
      $.post('<%= url_for(:action => 'director_completion') %>/' + $("#search_field").val() , function(data) {
        $("#results").html(data);
      });
    });
  })
// ]]>
</script>

app/views/directors/new.html.haml
- title 'New Director'
= render :partial => "form", :locals => { :director => @director }

app/views/directors/show.html.haml
= title @director.name

.composer-profile
  .image
    = image_tag(@director.image.attachment.url(:small)) if @director.image
  .description
    %h1= @director.name

= link_to t(:edit), edit_director_path(@director)
|
= link_to t(:back), directors_path

#tabs
  %ul
    %li
      %a{:href => "#user-albums"}= "My albums (#{@user_albums.size})"
    %li
      %a{:href => "#albums"}= "Albums (#{@albums.size})"
    %li
      %a{:href => "#description"}= t('description')
    %li
      %a{:href => "#discussions"}= "#{t('discussions_title')} (#{@director.discussions.size})"


  #user-albums
    = paginate @user_albums

    %table.data_table
      = render :partial => 'user_albums/album_headers'
      = render :partial => @user_albums

    = paginate @user_albums
    .clear

  #albums
    = paginate @albums

    %table.data_table
      = render :partial => 'albums/album_headers'
      = render :partial => @albums

    = paginate @albums
    .clear

  #description
    = @director.description

  #discussions
    = render :partial => 'discussions/form', :locals => {:discussable => @director}
    .user-discussions= render :partial => @director.discussions
    .clear

:javascript
  $(function() {
  $("#tabs").tabs();
  });