config/routes.rb
Classical::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'

  resources :authentications, :only => [:create, :destroy]

  devise_for :users

  resource :user do
    resources :user_albums
  end

  resources :instruments do
    resources :discussions
  end

  resources :composers do
    resources :discussions
  end

  resources :obra_types do
    resources :discussions
  end

  resources :solists do
    resources :discussions
  end

  resources :directors do
    resources :discussions
  end

  resources :orchestras do
    resources :discussions
  end

  resources :albums do
    resources :discussions
    resources :user_albums, :only => [:new]
  end

  resources :user_albums

  resources :app_languages

  #TODO Refactor this routes!!!

  match 'composers/composers_completion/', :to =>  "composers#composers_completion"
  match 'composers/composers_completion/:prefix', :to =>  "composers#composers_completion"

  match 'obra_types/obra_type_completion/', :to =>  "obra_types#obra_type_completion"
  match 'obra_types/obra_type_completion/:prefix', :to =>  "obra_types#obra_type_completion"

  match 'solists/solist_completion/', :to =>  "solists#solist_completion"
  match 'solists/solist_completion/:prefix', :to =>  "solists#solist_completion"

  match 'directors/director_completion/', :to =>  "directors#director_completion"
  match 'directors/director_completion/:prefix', :to =>  "directors#director_completion"

  match 'orchestras/orchestra_completion/', :to =>  "orchestras#orchestra_completion"
  match 'orchestras/orchestra_completion/:prefix', :to =>  "orchestras#orchestra_completion"

  match 'instruments/instrument_completion/', :to =>  "instruments#instrument_completion"
  match 'instruments/instrument_completion/:prefix', :to =>  "instruments#instrument_completion"

  #END :)

  root :to => 'user_albums#index'
end

app/models/solist.rb
# == Schema Information
#
# Table name: solists
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Solist < ActiveRecord::Base
  has_many :albums
  has_many :discussions, :as => :discussable
  has_one :image, :as => :imageable

  accepts_nested_attributes_for :image, :allow_destroy => true

  validates :name, :presence => true, :uniqueness => true

  def to_s
    self.name
  end
end

app/controllers/solists_controller.rb
class SolistsController < ApplicationController
  before_filter :find_solist,  :only => [:show, :edit, :update, :destroy]

  def index
    @solists = Solist.order(:name).page(params[:page])
  end

  def new
    @solist = Solist.new
  end

  def edit
  end

  def show
    conditions = {"album_solist_id_equals" => @solist.id}
    conditions.merge!(params[:search]) if params[:search] && params[:search][:album_solist_id_equals]
    @user_album_search = current_user.user_albums.search(conditions)
    @user_albums = @user_album_search.page(params[:page])

    conditions = {"solist_id_equals" => @solist.id}
    conditions.merge!(params[:search]) if params[:search] && params[:search][:solist_id_equals]
    @search = Album.search(conditions)
    @albums = @search.page(params[:page])
  end

  def solist_completion
    @solists = Solist.search(:name_starts_with => params[:prefix])

    if @solists.length == 0
      render :text => I18n.t(:no_results)
    else
      render :partial => @solists.relation
    end
  end

  def create
    @solist = Solist.new(params[:solist])

    respond_to do |format|
      if @solist.save
        format.html { redirect_to(@solist, :notice => I18n.t('.create_msg')) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @solist.update_attributes(params[:solist])
        format.html { redirect_to(@solist, :notice => I18n.t('.update_msg')) }
    else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @solist.destroy

     respond_to do |format|
       format.html { redirect_to(solists_url) }
     end
  end

  private
    def find_solist
      @solist = Solist.find(params[:id])
    end
end

app/helpers/solists_helper.rb
module SolistsHelper
end

app/views/solists/_form.html.haml
.form
  %h2= t :solist
  = form_for solist do |f|
    = errors_for solist
    .form_row
      = f.label :name
      = f.text_field :name, :class => :text

    .form_row
      = f.label :description
      = f.text_area :description, :class => :text

    .form_row_submit
      = f.submit :class => 'button'

= link_to t(:back), solists_path

app/views/solists/_solist.html.haml
%tr
  %td= link_to solist.name, solist, :id => 'link_to_data'
  %td
    = link_to edit_solist_path(solist) do
      = image_tag 'edit.gif'
      = t(:edit)
  %td
    = link_to solist, :confirm => t('delete_msg', :name => solist.name), :method => :delete do
      = image_tag 'delete.gif'
      = t(:delete)

app/views/solists/edit.html.haml
= title "#{t :editing} - #{@solist.name}"

= render :partial => "form", :locals => { :solist => @solist }

app/views/solists/index.html.erb
<%= title t :solists %>
<h1><%= t :solists %></h1>

<p>
  <%= link_to t(:new), new_solist_path %>
</p>

<%= form_tag nil, :class => 'search-form' do %>
  <%= t :search %>
  <%= text_field_tag :search_field %>
<% end -%>

<div class="paginator">
  <%= paginate @solists %>
</div>

<table class="data_table">
  <tr>
    <th><%= t :name %> </th>
    <th colspan=2><%= t :options %> </th>
  </tr>
  <tbody id="results">
    <%= render :partial => @solists %>
  </tbody>
</table>

<%= paginate @solists %>

<script type="text/javascript" language="javascript" charset="utf-8">
// <![CDATA[
  $(document).ready(function(){
    // when the #search field changes
    $("#search_field").live('keyup', function() {
      // make a POST call and replace the content
      $.post('<%= url_for(:action => 'solist_completion') %>/' + $("#search_field").val() , function(data) {
        $("#results").html(data);
      });
    });
  })
// ]]>
</script>

app/views/solists/new.html.haml
- title 'New Solist'
= render :partial => "form", :locals => { :solist => @solist }

app/views/solists/show.html.haml
= title @solist.name

.composer-profile
  .image
    = image_tag(@solist.image.attachment.url(:small)) if @solist.image
  .description
    %h1= @solist.name

= link_to t(:edit), edit_solist_path(@solist)
|
= link_to t(:back), solists_path

#tabs
  %ul
    %li
      %a{:href => "#user-albums"}= "My albums (#{@user_albums.size})"
    %li
      %a{:href => "#albums"}= "Albums (#{@albums.size})"
    %li
      %a{:href => "#description"}= t('description')
    %li
      %a{:href => "#discussions"}= "#{t('discussions_title')} (#{@solist.discussions.size})"

  #user-albums
    = paginate @user_albums

    %table.data_table
      = render :partial => 'user_albums/album_headers'
      = render :partial => @user_albums

    = paginate @user_albums
    .clear

  #albums
    = paginate @albums

    %table.data_table
      = render :partial => 'albums/album_headers'
      = render :partial => @albums

    = paginate @albums
    .clear

  #description
    = @solist.description

  #discussions
    = render :partial => 'discussions/form', :locals => {:discussable => @solist}
    .user-discussions= render :partial => @solist.discussions
    .clear

:javascript
  $(function() {
  $("#tabs").tabs();
  });