config/routes.rb
Classical::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'

  resources :authentications, :only => [:create, :destroy]

  devise_for :users

  resource :user do
    resources :user_albums
  end

  resources :instruments do
    resources :discussions
  end

  resources :composers do
    resources :discussions
  end

  resources :obra_types do
    resources :discussions
  end

  resources :solists do
    resources :discussions
  end

  resources :directors do
    resources :discussions
  end

  resources :orchestras do
    resources :discussions
  end

  resources :albums do
    resources :discussions
    resources :user_albums, :only => [:new]
  end

  resources :user_albums

  resources :app_languages

  #TODO Refactor this routes!!!

  match 'composers/composers_completion/', :to =>  "composers#composers_completion"
  match 'composers/composers_completion/:prefix', :to =>  "composers#composers_completion"

  match 'obra_types/obra_type_completion/', :to =>  "obra_types#obra_type_completion"
  match 'obra_types/obra_type_completion/:prefix', :to =>  "obra_types#obra_type_completion"

  match 'solists/solist_completion/', :to =>  "solists#solist_completion"
  match 'solists/solist_completion/:prefix', :to =>  "solists#solist_completion"

  match 'directors/director_completion/', :to =>  "directors#director_completion"
  match 'directors/director_completion/:prefix', :to =>  "directors#director_completion"

  match 'orchestras/orchestra_completion/', :to =>  "orchestras#orchestra_completion"
  match 'orchestras/orchestra_completion/:prefix', :to =>  "orchestras#orchestra_completion"

  match 'instruments/instrument_completion/', :to =>  "instruments#instrument_completion"
  match 'instruments/instrument_completion/:prefix', :to =>  "instruments#instrument_completion"

  #END :)

  root :to => 'user_albums#index'
end

app/models/user_album.rb
# == Schema Information
#
# Table name: user_albums
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  album_id   :integer
#  cd_number  :integer
#  location   :string(255)
#  favorite   :boolean
#  review_id  :integer
#  rating     :integer
#  created_at :datetime
#  updated_at :datetime
#

class UserAlbum < ActiveRecord::Base
  belongs_to :user
  belongs_to :album

  accepts_nested_attributes_for :album

  validates :user_id, :presence => true, :uniqueness => {:scope => :album_id}
  validates :cd_number, :numericality => true, :allow_blank => true
end

app/controllers/user_albums_controller.rb
class UserAlbumsController < ApplicationController
  before_filter :find_user_album, :only => [:show, :edit, :update]

  def index
    if params[:search] || params[:type]
      params[:search] = {"album_#{params[:type]}_contains" => params['query']} if params[:search].blank?
      type_key = params[:search].keys.grep(/contains/).first
      @query = params[:search][type_key]
      @type = type_key[6..-10] if type_key
    end

    params[:search] ||= {}
    params[:search][:meta_sort] ||= 'name.asc'

    @user_album_search = current_user.user_albums.search(params[:search])
    @user_albums = @user_album_search.page(params[:page])
  end

  def show
    @album = @user_album.album
  end

  def new
    @album = Album.find(params[:album_id])
    @user_album = current_user.user_albums.new(:album => @album)

    if !@user_album.save
      redirect_to(root_path, :notice => I18n.t('.duplicated_album')) and return
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user_album.update_attributes(params[:user_album])
        format.html { redirect_to @user_album, :notice => I18n.t('.update_msg') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  private

  def find_user_album
    @user_album = UserAlbum.find(params[:id])
  end
end

app/views/user_albums/_album_headers.html.haml
%tr
  %th= sort_link @user_album_search, :album_name, t(:name)
  - unless @section == 'composers'
    %th= sort_link @user_album_search, :album_composer_name, t(:composer)
  - unless @section == 'obra_types'
    %th= sort_link @user_album_search, :album_obra_type_name, t(:obra_type)
  - unless @section == 'orchestras'
    %th= sort_link @user_album_search, :album_orchestra_name, t(:orchestra)
  - unless @section == 'directors'
    %th= sort_link @user_album_search, :album_director_name, t(:director)
  - unless @section == 'solists'
    %th= sort_link @user_album_search, :album_solist_name, t(:solist)
  %th= sort_link @user_album_search, :album_number, t(:number)
  %th= sort_link @user_album_search, :album_opus_number, t(:opus_number)
  %th= sort_link @user_album_search, :cd_number

app/views/user_albums/_form.html.erb
<div class='form'>
<%= form_for @user_album do |f| -%>
  <%= f.fields_for :album do |builder| %>
    <div class='form_row'>
      <%= builder.label :composer %>
      <%= builder.select :composer_id, Composer.find(:all, :order => :name).collect{|composer| [composer.name, composer.id]} %>
    </div>
    <div class='form_row'>
      <%= builder.label :obra_type %>
      <%= builder.select :obra_type_id, ObraType.find(:all, :order => :name).collect{|obra_type| [obra_type.name, obra_type.id] } %>
    </div>
    <div class='form_row'>
      <%= builder.label :name %>
      <%= builder.text_field :name, :class => :text %>
    </div>
    <div class='form_row'>
      <%= builder.label :music_tone %>
      <%= builder.text_field :music_tone, :class => :text %>
    </div>
    <div class='form_row'>
      <%= builder.label :obra_number %>
      <%= builder.text_field :obra_number, :class => :text %>
    </div>
    <div class='form_row'>
      <%= builder.label :opus_number %>
      <%= builder.text_field :opus_number, :class => :text %>
    </div>
    <div class='form_row'>
      <%= builder.label :instrument %>
      <%= builder.select :instrument_id, Instrument.find(:all, :order => :name).collect{|instrument| [instrument.name, instrument.id] } %>
    </div>
    <div class='form_row'>
      <%= builder.label :solist %>
      <%= builder.select :solist_id, Solist.find(:all, :order => :name).collect{|solist| [solist.name, solist.id] } %>
    </div>
    <div class='form_row'>
      <%= builder.label :director %>
      <%= builder.select :director_id, Director.find(:all, :order => :name).collect{|director| [director.name, director.id] } %>
    </div>
    <div class='form_row'>
      <%= builder.label :orchestra %>
      <%= builder.select :orchestra_id, Orchestra.find(:all, :order => :name).collect{|orchestra| [orchestra.name, orchestra.id] } %>
    </div>
  <% end -%>

  <div class='form_row'>
    <%= f.label :cd_number %>
    <%= f.text_field :cd_number, :class => :text %>
  </div>

  <div class='form_row'>
    <%= f.label :location %>
    <%= f.text_field :location, :class => :text %>
  </div>

  <div class='form_row'>
    <%= f.label :favorite %>
    <%= f.check_box :favorite, :class => :text %>
  </div>

  <div class='form_row_submit'>
    <%= f.submit :class => 'button'%>
  </div>
<% end -%>
</div>

<script type="text/javascript" language="javascript" charset="utf-8">
// <![CDATA[
$(document).ready(function() {
  $("#user_album_album_attributes_obra_type_id").combobox();
  $("#user_album_album_attributes_composer_id").combobox();
  $("#user_album_album_attributes_solist_id").combobox();
  $("#user_album_album_attributes_director_id").combobox();
  $("#user_album_album_attributes_orchestra_id").combobox();
  $("#user_album_album_attributes_instrument_id").combobox();
});
// ]]>
</script>

app/views/user_albums/_user_album.html.haml
%tr
  %td= link_to user_album.album.name, user_album, :id => 'link_to_data'

  - unless @section == 'composers'
    %td= link_to(user_album.album.composer.name, user_album.album.composer, :id => 'link_to_data')

  - unless @section == 'obra_types'
    %td= link_to user_album.album.obra_type.to_s, user_album.album.obra_type, :id => 'link_to_data'

  - unless @section == 'orchestras'
    %td= link_to user_album.album.orchestra.to_s, user_album.album.orchestra, :id => 'link_to_data'

  - unless @section == 'directors'
    %td= link_to user_album.album.director.to_s, user_album.album.director, :id => 'link_to_data'

  - unless @section == 'solists'
    %td= link_to user_album.album.solist.to_s, user_album.album.solist, :id => 'link_to_data'

  %td= user_album.album.obra_number
  %td= user_album.album.opus_number
  %td= user_album.cd_number

app/views/user_albums/edit.html.erb
<%= render :partial => "form" %>

app/views/user_albums/index.html.haml
= title t(:my_albums)

%h1= t :my_albums

%p= link_to "#{t :new}", new_album_path

= form_tag user_user_albums_path(current_user), :method => :get, :class => 'search-form'  do
  %p
    = t :search
    = text_field_tag :query, @query
    = select_tag :type, options_for_select([['nombre', 'name'], ['director', 'director_name'], ['solista', 'solist_name'], ['orquesta', 'orchestra_name'], ['compositor', 'composer_name']], @type)
    = submit_tag 'Buscar'


= will_paginate @user_albums, :previous_label => t('previous'), :next_label => t('next') if @user_albums.respond_to? 'total_pages'

%table.data_table
  = render :partial => 'album_headers'
  %tbody#results= render :partial => @user_albums

= will_paginate @user_albums, :previous_label => t('previous'), :next_label => t('next') if @user_albums.respond_to? 'total_pages'

app/views/user_albums/new.html.erb
<%= render :partial => "form" %>

app/views/user_albums/show.html.haml
= title @album.name
%h2= @album.name

#tabs
  %ul
    %li
      %a{:href => "#info"}= t('info')
    %li
      %a{:href => "#review-listeners"}= "#{t('reviews_listeners')} (#{@album.users.size})"
    %li
      %a{:href => "#discussions"}= "#{t('discussions_title')} (#{@album.discussions.size})"

  #info
    .form.album
      .cover_art
        = image_tag @album.image.attachment.url(:thumb) if @album.image
      %p
        %b= Album.human_attribute_name :composer
        = link_to @album.composer.name, @album.composer if @album.composer
      %p
        %b= Album.human_attribute_name :obra_type
        = link_to @album.obra_type.name, @album.obra_type if @album.obra_type
      %p
        %b= Album.human_attribute_name :music_tone
        = @album.music_tone
      %p
        %b= Album.human_attribute_name :obra_number
        = @album.obra_number
      %p
        %b= Album.human_attribute_name :opus_number
        = @album.opus_number
      %p
        %b= Album.human_attribute_name :instrument
        = link_to @album.instrument.name, @album.instrument if @album.instrument
      %p
        %b= Album.human_attribute_name :solist
        = link_to @album.solist.name, @album.solist if @album.solist
      %p
        %b= Album.human_attribute_name :director
        = link_to @album.director.name, @album.director if @album.director
      %p
        %b= Album.human_attribute_name :orchestra
        = link_to @album.orchestra.name, @album.orchestra if @album.orchestra
      %p
        %b= UserAlbum.human_attribute_name :cd_number
        = @user_album.cd_number
      %p
        %b= UserAlbum.human_attribute_name :location
        = @user_album.location
      %p
        %b= UserAlbum.human_attribute_name :favorite
        = @user_album.favorite

      = link_to t(:edit), edit_user_album_path(@user_album)
      |
      = link_to t(:back), albums_path

  #review-listeners
    = render :partial => @album.users

  #discussions
    = render :partial => 'discussions/form', :locals => {:discussable => @album}
    .user-discussions= render :partial => @album.discussions
    .clear

:javascript
  $(function() {
    $("#tabs").tabs();
  });