config/routes.rb
Classical::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'

  resources :authentications, :only => [:create, :destroy]

  devise_for :users

  resource :user do
    resources :user_albums
  end

  resources :instruments do
    resources :discussions
  end

  resources :composers do
    resources :discussions
  end

  resources :obra_types do
    resources :discussions
  end

  resources :solists do
    resources :discussions
  end

  resources :directors do
    resources :discussions
  end

  resources :orchestras do
    resources :discussions
  end

  resources :albums do
    resources :discussions
    resources :user_albums, :only => [:new]
  end

  resources :user_albums

  resources :app_languages

  #TODO Refactor this routes!!!

  match 'composers/composers_completion/', :to =>  "composers#composers_completion"
  match 'composers/composers_completion/:prefix', :to =>  "composers#composers_completion"

  match 'obra_types/obra_type_completion/', :to =>  "obra_types#obra_type_completion"
  match 'obra_types/obra_type_completion/:prefix', :to =>  "obra_types#obra_type_completion"

  match 'solists/solist_completion/', :to =>  "solists#solist_completion"
  match 'solists/solist_completion/:prefix', :to =>  "solists#solist_completion"

  match 'directors/director_completion/', :to =>  "directors#director_completion"
  match 'directors/director_completion/:prefix', :to =>  "directors#director_completion"

  match 'orchestras/orchestra_completion/', :to =>  "orchestras#orchestra_completion"
  match 'orchestras/orchestra_completion/:prefix', :to =>  "orchestras#orchestra_completion"

  match 'instruments/instrument_completion/', :to =>  "instruments#instrument_completion"
  match 'instruments/instrument_completion/:prefix', :to =>  "instruments#instrument_completion"

  #END :)

  root :to => 'user_albums#index'
end

app/models/instrument.rb
# == Schema Information
#
# Table name: instruments
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Instrument < ActiveRecord::Base
  has_many :albums
  has_many :discussions, :as => :discussable

  validates :name, :presence => true, :uniqueness => true
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_filter :find_instrument,  :only => [:show, :edit, :update, :destroy ]

  # GET /instruments
  # GET /instruments.xml
  def index
    @instruments = Instrument.order(:name).page(params[:page])
  end

  def show
    conditions = {"album_instrument_id_equals" => @instrument.id}
    conditions.merge!(params[:search]) if params[:search] && params[:search][:album_instrument_id_equals]
    @user_album_search = current_user.user_albums.search(conditions)
    @user_albums = @user_album_search.page(params[:page])

    conditions = {"instrument_id_equals" => @instrument.id}
    conditions.merge!(params[:search]) if params[:search] && params[:search][:instrument_id_equals]
    @search = Album.search(conditions)
    @albums = @search.page(params[:page])
  end

  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit

  end

  # POST /instruments
  # POST /instruments.xml
  def create
    @instrument = Instrument.new(params[:instrument])

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to(@instrument, :notice => I18n.t('.create_msg')) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /instruments/1
  # PUT /instruments/1.xml
  def update
    respond_to do |format|
      if @instrument.update_attributes(params[:instrument])
        format.html { redirect_to(@instrument, :notice => I18n.t('.update_msg')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.xml
  def destroy
    @instrument.destroy

    respond_to do |format|
      format.html { redirect_to(instruments_url) }
    end
  end

  def instrument_completion
    @instruments = Instrument.search(:name_starts_with => params[:prefix])

    if @instruments.length == 0
      render :text => I18n.t(:no_results)
    else
      render :partial => @instruments.relation
    end
  end

  private

  def find_instrument
    @instrument = Instrument.find(params[:id])
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.haml
.form
  %h2= t :instrument

  = form_for instrument do |f|
    = errors_for instrument
    .form_row
      = f.label :name
      = f.text_field :name, :class => :text

    .form_row
      = f.label :description
      = f.text_area :description, :class => :text

    .form_row_submit
      = f.submit :class => 'button'

= link_to t(:back), instruments_path

app/views/instruments/_instrument.html.haml
%tr
  %td= link_to instrument.name, instrument, :id => 'link_to_data'
  %td
    = link_to edit_instrument_path(instrument) do
      = image_tag 'edit.gif'
      = t(:edit)
  %td
    = link_to instrument, :confirm => t('delete_msg', :name => instrument.name), :method => :delete do
      = image_tag 'delete.gif'
      = t(:delete)

app/views/instruments/edit.html.haml
= title "#{t :editing} - #{@instrument.name}"

= render :partial => "form", :locals => { :instrument => @instrument }

app/views/instruments/index.html.erb
<%= title t :instruments %>
<h1><%= t :instruments %></h1>

<p>
  <%= link_to t(:new), new_instrument_path %>
</p>

<%= form_tag nil, :class => 'search-form' do %>
  <%= t :search %>
  <%= text_field_tag :search_field %>
<% end -%>

<div class="paginator">
  <%= paginate @instruments %>
</div>

<table class="data_table">
  <tr>
    <th><%= t :name %> </th>
    <th colspan=2><%= t :options %> </th>
  </tr>
  <tbody id="results">
    <%= render :partial => @instruments %>
  </tbody>
</table>

<%= paginate @instruments %>

<script type="text/javascript" language="javascript" charset="utf-8">
// <![CDATA[
  $(document).ready(function(){
    // when the #search field changes
    $("#search_field").live('keyup', function() {
      // make a POST call and replace the content
      $.post('<%= url_for(:action => 'instrument_completion') %>/' + $("#search_field").val() , function(data) {
        $("#results").html(data);
      });
    });
  })
// ]]>
</script>

app/views/instruments/new.html.haml
- title 'New Instrument'
= render :partial => "form", :locals => { :instrument => @instrument }

app/views/instruments/show.html.haml
= title @instrument.name

%h1= @instrument.name

= link_to t(:edit), edit_instrument_path(@instrument)
|
= link_to t(:back), instruments_path

#tabs
  %ul
    %li
      %a{:href => "#user-albums"}= "My albums (#{@user_albums.size})"
    %li
      %a{:href => "#albums"}= "Albums (#{@albums.size})"
    %li
      %a{:href => "#description"}= t('description')
    %li
      %a{:href => "#discussions"}= "#{t('discussions_title')} (#{@instrument.discussions.size})"

  #user-albums
    = paginate @user_albums

    %table.data_table
      = render :partial => 'user_albums/album_headers'
      = render :partial => @user_albums

    = paginate @user_albums
    .clear

  #albums
    = paginate @albums

    %table.data_table
      = render :partial => 'albums/album_headers'
      = render :partial => @albums

    = paginate @albums
    .clear

  #description
    = @instrument.description

  #discussions
    = render :partial => 'discussions/form', :locals => {:discussable => @instrument}
    .user-discussions= render :partial => @instrument.discussions
    .clear

:javascript
  $(function() {
  $("#tabs").tabs();
  });